[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/sprouthub"
  to = "/projects/sprouthub"
  status = 301

[[redirects]]
  from = "/paperedge"
  to = "/projects/paperedge"
  status = 301

[[redirects]]
  from = "/thinx"
  to = "/projects/thinx"
  status = 301

[[redirects]]
  from = "/codenation"
  to = "/projects/codenation"
  status = 301

[[redirects]]
  from = "/funnelleasing"
  to = "/projects/funnelleasing"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
